version: '3.9'

services:
  oasis-node-testnet:
    container_name: oasis-node-testnet
    image: hashfabric/oasis-node:v21.3.5
    build: 
      context: .
      args: 
        - DEV_IMAGE_VERSION=stable-21.3.x
        - CORE_VERSION=v21.3.5
        - CIPHER_VERSION=v2.0.0-alpha2
        - EMERALD_VERSION=v3.0.0-alpha
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
      - seccomp=unconfined
    volumes:
      - /data/oasis/testnet:/node
    working_dir: /node/data
    ports:
      - "46656:46656" # P2P (TCP)
      - "127.0.0.1:46657:26657" # RPC (TCP)
      - "30001:30001"
      - "30002:30002"
    ulimits:
      nofile:
        soft: "102400"
        hard: "102400"
    command: oasis-node
      --datadir /node/data
      --log.level warn
      --log.format json 
      --genesis.file /node/genesis.json 
      --consensus.tendermint.p2p.seed 05EAC99BB37F6DAAD4B13386FF5E087ACBDDC450@34.86.165.6:26656
      --consensus.tendermint.core.listen_address tcp://0.0.0.0:46656 
      --consensus.tendermint.core.external_address tcp://${EXTIP}:46656 
      --consensus.validator
      --worker.registration.entity /node/entity/entity.json 
      --worker.client.port 30001 
      --worker.client.addresses $EXTIP:30001
      --worker.p2p.enabled
      --worker.p2p.port 30002
      --worker.p2p.addresses $EXTIP:30002
      --worker.compute.enabled=true
      --worker.storage.enabled=true
      --runtime.supported 0000000000000000000000000000000000000000000000000000000000000000
      --runtime.supported 00000000000000000000000000000000000000000000000072c8215e60d5bca7
      --runtime.paths 0000000000000000000000000000000000000000000000000000000000000000=/usr/local/bin/cipher-paratime
      --runtime.paths 00000000000000000000000000000000000000000000000072c8215e60d5bca7=/usr/local/bin/emerald-paratime
      --debug.dont_blame_oasis
